//! Data types for the Agent Runtime abstraction.
//!
//! These types define the interface between Ergatai and pluggable execution backends.
//! They are backend-agnostic — each backend interprets them according to its own model.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Specification for creating a new agent workspace.
///
/// A workspace is the execution environment for an agent — it could be a tmux session,
/// a Docker container, an SSH host, or a Kubernetes pod, depending on the backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceSpec {
    /// Unique workspace identifier (e.g., "dag-task-123-agent-a")
    pub id: String,

    /// Working directory mounted/available in the workspace
    pub work_dir: PathBuf,

    /// Environment variables to set in the workspace
    pub env: HashMap<String, String>,

    /// Resource limits (CPU, memory, disk) — backend-specific enforcement
    pub resources: ResourceLimits,

    /// Backend-specific configuration (JSON for extensibility)
    pub backend_config: serde_json::Value,
}

/// Resource limits for a workspace.
///
/// All fields are optional — `None` means "no limit" or "use backend default".
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ResourceLimits {
    /// CPU cores (e.g., 2.5 = 2.5 cores)
    pub cpu_cores: Option<f64>,

    /// Memory in megabytes
    pub memory_mb: Option<u64>,

    /// Disk space in megabytes
    pub disk_mb: Option<u64>,
}

/// Opaque handle to a created workspace.
///
/// The `metadata` field contains backend-specific identifiers (e.g., tmux session name,
/// Docker container ID, SSH host).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkspaceHandle {
    /// Workspace ID (matches `WorkspaceSpec.id`)
    pub id: String,

    /// Backend name that created this workspace
    pub backend: String,

    /// Backend-specific metadata (e.g., `{"session": "ergatai-abc"}`)
    pub metadata: HashMap<String, String>,
}

/// Opaque handle to a running agent.
///
/// Contains the workspace handle plus agent-specific identifiers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentHandle {
    /// The workspace this agent runs in
    pub workspace: WorkspaceHandle,

    /// Unique agent identifier (generated by the runtime)
    pub agent_id: String,

    /// Process identifier (PID, container ID, etc.) — backend-specific
    pub process_id: Option<String>,

    /// Backend-specific metadata (e.g., `{"pane_id": "%3"}`)
    pub metadata: HashMap<String, String>,
}

/// Agent lifecycle state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AgentState {
    /// Agent is being set up (workspace created, process starting)
    Starting,

    /// Agent is running and accepting work
    Running,

    /// Agent is being stopped (graceful shutdown in progress)
    Stopping,

    /// Agent has exited (cleanly or otherwise)
    Stopped,

    /// Agent failed to start or crashed with an error message
    Failed(String),
}

/// Result of waiting for an agent to exit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WaitResult {
    /// Agent exited normally with an exit code
    Exited {
        /// Exit code (0 = success)
        code: i32,
    },

    /// Agent was killed by a signal
    Signaled {
        /// Signal number (e.g., 9 = SIGKILL, 15 = SIGTERM)
        signal: i32,
    },

    /// Wait timed out before agent exited
    Timeout,

    /// Error occurred while waiting
    Error(String),
}

/// Backend capability flags.
///
/// Callers should check these before attempting operations to provide graceful degradation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BackendCapabilities {
    /// Can inject messages into a running agent (e.g., tmux send-keys)
    pub supports_message_injection: bool,

    /// Can capture agent output (e.g., tmux capture-pane, docker logs)
    pub supports_output_capture: bool,

    /// Can enforce resource limits (e.g., cgroups, Docker limits)
    pub supports_resource_limits: bool,

    /// Can reuse a workspace for multiple agents sequentially
    pub supports_workspace_reuse: bool,

    /// Can isolate agent network access
    pub supports_network_isolation: bool,

    /// Maximum concurrent agents (None = unlimited)
    pub max_concurrent_agents: Option<usize>,
}

/// Agent information tracked by the runtime facade.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentInfo {
    /// Unique agent ID (runtime-generated)
    pub agent_id: String,

    /// Workspace ID this agent belongs to
    pub workspace_id: String,

    /// Backend handle for this agent
    pub handle: AgentHandle,

    /// Current lifecycle state
    pub state: AgentState,

    /// Optional task ID (for DAG orchestration)
    pub task_id: Option<String>,

    /// Optional MCP agent ID (for MCP-connected agents)
    pub mcp_agent_id: Option<String>,

    /// When this agent was created
    pub created_at: chrono::DateTime<chrono::Utc>,
}
