/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 权限请求（从 agent 发起到前端） */
export interface NapiPermissionRequest {
  sessionId: string
  requestId: string
  toolName?: string
  options: Array<NapiPermissionOption>
}
export interface NapiPermissionOption {
  optionId: string
  label: string
}
/** NAPI 导出的 Session 事件（data 序列化为 JSON 字符串） */
export interface NapiSessionEvent {
  sessionId: string
  eventType: string
  data: string
}
export interface NapiSessionInfo {
  sessionId: string
  agentName: string
  cwd: string
  status: string
  title?: string
  updatedAt?: string
}
/** 本地保存的会话元数据（用于离线浏览和历史记录） */
export interface PersistedSession {
  sessionId: string
  agentName: string
  cwd: string
  title?: string
  createdAt: string
  updatedAt: string
}
/** Agent 配置（包含表单字段） */
export interface AgentConfig {
  name: string
  command: string
  args: Array<string>
  env: Record<string, string>
  baseUrl?: string
  model?: string
  apiKey?: string
  proxy?: string
  /** 自定义提示词 / persona */
  persona?: string
  /** Agent 类型标识（claude-code / codex / opencode / custom） */
  agentType?: string
  /** 头像（base64 data URL 或文件路径） */
  avatar?: string
}
/** Agent 基本信息（用于列表展示） */
export interface AgentInfo {
  name: string
  command: string
  args: Array<string>
  source: string
  /** Agent 类型标识 */
  agentType?: string
  /** 头像（base64 data URL 或文件路径） */
  avatar?: string
  /** 模型名称 */
  model?: string
}
export interface NapiAgentInfo {
  agentId: string
  state: string
  alive: boolean
  canAcceptTask: boolean
}
/** Skill info returned to renderer */
export interface SkillInfo {
  id: string
  name: string
  description: string
  category: string
  path: string
}
/** Skill detail with markdown content */
export interface SkillDetail {
  name: string
  description: string
  content: string
  path: string
}
/** Scan all skill sources */
export declare function scanSkills(): Array<SkillInfo>
/** Get skill detail by name */
export declare function getSkillDetail(name: string): SkillDetail
/** MCP server information */
export interface McpServerInfo {
  id: string
  name: string
  category: string
  status: string
  command?: string
  args?: Array<string>
  env?: Record<string, string>
}
/** Built-in service info */
export interface BuiltinServiceInfo {
  name: string
  binaryPath: string
  status: string
  version?: string
}
/** Scan all MCP servers from configs */
export declare function scanMcpServers(): Array<McpServerInfo>
/** Get a specific MCP server's configuration */
export declare function getMcpServerConfig(name: string): McpServerInfo | null
/** Check if a built-in service is available */
export declare function checkBuiltinServices(): Array<BuiltinServiceInfo>
/** Start an MCP server (simplified - logs the command to be executed) */
export declare function startMcpServer(name: string): string
/** Stop an MCP server */
export declare function stopMcpServer(name: string): void
/** 扫描本地已注册的 agent */
export declare function scanLocalAgents(): Array<AgentInfo>
/** 获取指定 agent 的配置 */
export declare function getAgentConfig(name: string): AgentConfig
/** 保存 agent 配置 */
export declare function saveAgentConfig(config: AgentConfig): void
/** 生成启动脚本 */
export declare function generateLaunchScript(name: string): string
/**
 * 创建 ACP 会话（异步）
 * 返回 session_id
 */
export declare function acpCreateSession(agentName: string, cwd: string): Promise<string>
/** 发送 prompt 到指定会话 */
export declare function acpSendPrompt(sessionId: string, prompt: string): Promise<void>
/** 关闭指定会话 */
export declare function acpCloseSession(sessionId: string): Promise<boolean>
/** 列出所有活跃会话 */
export declare function acpListSessions(): Promise<Array<NapiSessionInfo>>
/** 关闭所有会话（优雅关闭） */
export declare function acpCloseAllSessions(): Promise<void>
/** 轮询 session 事件（TS 侧定时调用） */
export declare function acpPollEvents(): Array<NapiSessionEvent>
/** 从 agent 查询会话列表（通过 ACP session/list 协议） */
export declare function acpListAgentSessions(agentName: string, cwd?: string | undefined | null): Promise<Array<NapiSessionInfo>>
/** 加载已有会话（通过 ACP session/load 协议） */
export declare function acpLoadSession(agentName: string, sessionId: string, cwd: string): Promise<string>
/** 恢复已有会话（通过 ACP session/resume 协议） */
export declare function acpResumeSession(agentName: string, sessionId: string, cwd: string): Promise<string>
/** 响应权限请求（从前端发回给 agent） */
export declare function acpRespondPermission(sessionId: string, requestId: string, optionId?: string | undefined | null): Promise<void>
/** 设置会话模式 */
export declare function acpSetSessionMode(sessionId: string, modeId: string): Promise<void>
/** 设置会话配置选项 */
export declare function acpSetConfigOption(sessionId: string, configId: string, valueId: string): Promise<void>
/** 从 agent 删除会话（通过 ACP session/delete 协议）+ 清除本地持久化 */
export declare function acpDeleteSession(agentName: string, sessionId: string): Promise<void>
/** 获取本地持久化的会话列表 */
export declare function acpGetPersistedSessions(): Array<PersistedSession>
/** 保存会话元数据到本地 */
export declare function acpSaveSessionMeta(sessionId: string, agentName: string, cwd: string, title?: string | undefined | null): void
/** 更新会话标题 */
export declare function acpUpdateSessionTitle(sessionId: string, title: string): void
/** 注册 agent 到通信网络 */
export declare function networkRegister(agentId: string): Promise<void>
/** 注销 agent */
export declare function networkUnregister(agentId: string): Promise<void>
/** 发送任务给目标 agent */
export declare function networkSendTask(from: string, target: string, taskId: string, payload: string): Promise<void>
/** 发送任务结果 */
export declare function networkSendResult(from: string, target: string, taskId: string, payload: string): Promise<void>
/** 广播到频道 */
export declare function networkBroadcast(from: string, channel: string, data: string): Promise<void>
/** 列出所有 agent 及状态 */
export declare function networkListAgents(): Array<NapiAgentInfo>
/** 获取 agent 状态 */
export declare function networkGetState(agentId: string): string
/**
 * 使用 NATS 初始化通信网络（支持持久化）。
 * 必须在其他 network_* 调用前调用，且只能调用一次。
 */
export declare function networkInitNats(url: string, prefix: string): Promise<void>
/** 发送 AI 友好消息（自动推断意图、提取上下文） */
export declare function networkSendFriendly(from: string, target: string, content: string, intent?: string | undefined | null, expect?: string | undefined | null, constraints?: Array<string> | undefined | null): Promise<void>
/** 广播 AI 友好消息到频道 */
export declare function networkBroadcastFriendly(from: string, channel: string, content: string, intent?: string | undefined | null, expect?: string | undefined | null): Promise<void>
/** 创建任务（自动解析 AI 友好消息） */
export declare function networkCreateTask(from: string, content: string, expect?: string | undefined | null): string
/** 获取任务信息 */
export declare function networkGetTask(taskId: string): string | null
/** 列出所有任务 */
export declare function networkListTasks(): Array<string>
/** Submit a DAG for execution. Returns JSON array of submitted task IDs. */
export declare function dagSubmit(markdown: string): Promise<string>
/** Get DAG progress as a value between 0.0 and 1.0. */
export declare function dagProgress(): Promise<number>
/** Check if all nodes in the DAG are complete. */
export declare function dagIsComplete(): Promise<boolean>
/** Get AI-friendly status text for the current DAG. */
export declare function dagStatus(): Promise<string>
/** Get full DAG state as JSON. */
export declare function dagGetState(): Promise<string>

/** ACP Runtime availability status */
export type AcpAvailabilityStatus = 'available' | 'not_installed' | 'auth_required'
/** ACP Runtime auth status */
export type AuthStatus = 'logged_in' | 'logged_out' | 'not_applicable' | 'unknown'
/** ACP Runtime catalog entry */
export interface AcpRuntimeCatalogEntry {
  id: string
  label: string
  avatarUrl: string
  availability: AcpAvailabilityStatus
  command?: string | null
  binaryPath?: string | null
  installHint: string
  installInstructionsUrl: string
  hasInstallCommand: boolean
  authStatus: AuthStatus
  loginHint?: string | null
  source: string
}
/** Custom harness definition */
export interface HarnessDefinition {
  id: string
  label: string
  command: string
  args?: Array<string>
  envVars?: Record<string, string>
  avatarUrl?: string
  source: string
}
/** Global agent configuration */
export interface GlobalAgentConfig {
  envVars?: Record<string, string>
  provider?: string | null
  model?: string | null
  preferredRuntime?: string | null
}
/** Discover all available ACP runtimes and their status */
export declare function discoverAcpRuntimes(): Array<AcpRuntimeCatalogEntry>
/** Load the global agent configuration */
export declare function getGlobalAgentConfig(): Promise<GlobalAgentConfig>
/** Save the global agent configuration */
export declare function setGlobalAgentConfig(config: GlobalAgentConfig): Promise<void>
/** Save a custom harness definition */
export declare function saveCustomHarness(harness: HarnessDefinition): Promise<AcpRuntimeCatalogEntry>
/** Delete a custom harness by id */
export declare function deleteCustomHarness(id: string): Promise<void>
/** Install an ACP runtime by executing its predefined install command */
export declare function installAcpRuntime(runtimeId: string): Promise<string>
