//! DAG Markdown parser
//!
//! Parses structured Markdown format into TaskGraph.
//! ID (UUID) is auto-generated by the system.
//!
//! Format:
//! ```markdown
//! ## Task A
//! - **agent**: agent-a
//! - **task**: path/to/task-a.md
//! - **depends_on**: []
//!
//! ## Task B
//! - **agent**: agent-b
//! - **task**: path/to/task-b.md
//! - **depends_on**: [Task A]
//! ```

use std::collections::HashMap;

use crate::error::{ErgataiError, ErgataiResult};
use uuid::Uuid;

use crate::orchestration::dag_topology::{TaskGraph, TaskNode, TaskStatus};

/// Parse a Markdown DAG specification into a TaskGraph
pub fn parse_dag_markdown(content: &str) -> ErgataiResult<TaskGraph> {
    // Estimate capacity based on task headers (## or ###)
    let estimated_nodes = content.matches("## ").count() + content.matches("### ").count();
    let mut temp_nodes = Vec::with_capacity(estimated_nodes.max(8));
    let mut current_node: Option<TaskNodeBuilder> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip empty lines
        if trimmed.is_empty() {
            continue;
        }

        // Parse node header: ## Task description or ### Task description
        if trimmed.starts_with("# ") || trimmed.starts_with("## ") || trimmed.starts_with("### ") {
            // Check if it's a node header (## or ###) vs graph title (#)
            if trimmed.starts_with("## ") || trimmed.starts_with("### ") {
                // Save previous node
                if let Some(builder) = current_node.take() {
                    temp_nodes.push(builder.build_temp()?);
                }

                // Parse new node
                current_node = Some(parse_node_header(trimmed)?);
            }
            // else: graph title, skip for now
        }
        // Parse property: - **key**: value
        else if trimmed.starts_with("- **") {
            if let Some(ref mut builder) = current_node {
                parse_property(builder, trimmed)?;
            }
        }
    }

    // Save last node
    if let Some(builder) = current_node {
        temp_nodes.push(builder.build_temp()?);
    }

    if temp_nodes.is_empty() {
        return Err(ErgataiError::InvalidArgument(
            "No tasks found in markdown".to_string(),
        ));
    }

    // Check for duplicate task names before building UUID mapping
    let mut seen_names = std::collections::HashSet::new();
    for node in &temp_nodes {
        if !seen_names.insert(&node.id) {
            return Err(ErgataiError::InvalidArgument(format!(
                "Duplicate task name: '{}'",
                node.id
            )));
        }
    }

    // Build name-to-UUID mapping
    let mut name_to_uuid: HashMap<String, String> = HashMap::with_capacity(temp_nodes.len());
    for node in &temp_nodes {
        let uuid = Uuid::new_v4().to_string();
        name_to_uuid.insert(node.id.clone(), uuid);
    }

    // Create final nodes with UUIDs and updated depends_on
    let nodes: Vec<TaskNode> = temp_nodes
        .into_iter()
        .map(|mut node| {
            // Replace task name ID with UUID
            let uuid = name_to_uuid
                .get(&node.id)
                .cloned()
                .unwrap_or_else(|| node.id.clone());
            node.id = uuid;

            // Update depends_on references to use UUIDs
            node.depends_on = node
                .depends_on
                .iter()
                .map(|name| {
                    name_to_uuid
                        .get(name)
                        .cloned()
                        .unwrap_or_else(|| name.clone())
                })
                .collect();

            node
        })
        .collect();

    let graph = TaskGraph::new(nodes);
    graph.validate()?;

    Ok(graph)
}

/// Builder for TaskNode (collects properties before building)
struct TaskNodeBuilder {
    task: String, // Task description from header
    agent: Option<String>,
    task_path: Option<String>, // Path to task document
    parent: Option<String>,
    depends_on: Vec<String>, // Task names (will be mapped to UUIDs later)
    input: Option<String>,
    output: Option<String>,
    priority: Option<String>,
    timeout: Option<u64>,
    max_retries: Option<u32>,
    scope: Option<String>, // Phase 3: File access scope (glob pattern)
    metadata: HashMap<String, String>,
}

impl TaskNodeBuilder {
    fn new(task: String) -> Self {
        Self {
            task,
            agent: None,
            task_path: None,
            parent: None,
            depends_on: Vec::new(),
            input: None,
            output: None,
            priority: None,
            timeout: None,
            max_retries: None,
            scope: None,
            metadata: HashMap::new(),
        }
    }

    /// Build a temporary TaskNode with task name as ID (will be replaced with UUID)
    fn build_temp(self) -> ErgataiResult<TaskNode> {
        // Merge parent into depends_on if specified
        let mut depends_on = self.depends_on;
        if let Some(ref parent) = self.parent {
            if !depends_on.contains(parent) {
                depends_on.push(parent.clone());
            }
        }

        // Build metadata
        let mut metadata = self.metadata;
        if let Some(ref task_path) = self.task_path {
            metadata.insert("task_path".to_string(), task_path.clone());
        }
        if let Some(ref parent) = self.parent {
            metadata.insert("parent".to_string(), parent.clone());
        }

        // Use task name as temporary ID (will be replaced with UUID later)
        Ok(TaskNode {
            id: self.task.clone(), // Task name as temp ID
            agent: self.agent.unwrap_or_else(|| "agent".to_string()),
            task: self.task,
            status: TaskStatus::Pending,
            depends_on,
            input: self.input,
            output: self.output,
            result_path: None,
            max_retries: self.max_retries.unwrap_or(0),
            retry_count: 0,
            priority: self.priority,
            timeout: self.timeout,
            scope: self.scope, // Phase 3: File access scope
            metadata,
        })
    }
}

/// Parse node header: "## Task description" -> TaskNodeBuilder
/// ID (UUID) is auto-generated during build()
fn parse_node_header(line: &str) -> ErgataiResult<TaskNodeBuilder> {
    // Remove markdown header markers
    let task = line
        .strip_prefix("### ")
        .or_else(|| line.strip_prefix("## "))
        .map(str::trim)
        .ok_or_else(|| ErgataiError::InvalidArgument(format!("Invalid header format: {}", line)))?;

    if task.is_empty() {
        return Err(ErgataiError::InvalidArgument(format!(
            "Empty task description in: {}",
            line
        )));
    }

    Ok(TaskNodeBuilder::new(task.to_string()))
}

/// Parse a property line: "- **key**: value"
fn parse_property(builder: &mut TaskNodeBuilder, line: &str) -> ErgataiResult<()> {
    // Extract key and value
    let key_start = line.find("**").ok_or_else(|| {
        ErgataiError::InvalidArgument(format!("Missing ** in property: {}", line))
    })? + 2;
    let key_end = line[key_start..].find("**").ok_or_else(|| {
        ErgataiError::InvalidArgument(format!("Missing closing ** in property: {}", line))
    })? + key_start;

    let key = line[key_start..key_end].trim().to_string();

    // Find the value (after ": ")
    let value_start = line[key_end + 2..].find(':').ok_or_else(|| {
        ErgataiError::InvalidArgument(format!("Missing : in property '{}': {}", key, line))
    })? + key_end
        + 3;

    let value = line[value_start..].trim().to_string();

    match key.as_str() {
        "agent" => {
            builder.agent = Some(value);
        }
        "task" => {
            // task is the path to the task document
            builder.task_path = Some(value);
        }
        "parent" => {
            builder.parent = Some(value);
        }
        "depends_on" => {
            // Parse array: [n1, n2, n3]
            builder.depends_on = parse_array(&value)?;
        }
        "input" => {
            builder.input = Some(value);
        }
        "output" => {
            builder.output = Some(value);
        }
        "priority" => {
            builder.priority = Some(value);
        }
        "timeout" => {
            // Parse as seconds (integer) — warn on invalid values instead of silently ignoring
            match value.parse::<u64>() {
                Ok(v) => builder.timeout = Some(v),
                Err(_) => {
                    tracing::warn!(value = %value, key = %key, "Invalid timeout value in DAG markdown, ignoring");
                }
            }
        }
        "retry" | "max_retries" => match value.parse::<u32>() {
            Ok(v) => builder.max_retries = Some(v),
            Err(_) => {
                tracing::warn!(value = %value, key = %key, "Invalid retry count in DAG markdown, ignoring");
            }
        },
        "scope" => {
            // Phase 3: File access scope (glob pattern)
            // Validate the scope pattern
            match validate_scope_pattern(&value) {
                Ok(_) => builder.scope = Some(value),
                Err(e) => {
                    tracing::warn!(scope = %value, error = %e, "Invalid scope pattern in DAG markdown, ignoring");
                }
            }
        }
        _ => {
            // Store in metadata
            builder.metadata.insert(key, value);
        }
    }

    Ok(())
}

/// Parse array format: "[n1, n2, n3]" -> Vec<String>
fn parse_array(value: &str) -> ErgataiResult<Vec<String>> {
    let trimmed = value.trim();

    // Remove [ and ]
    let inner = if trimmed.starts_with('[') && trimmed.ends_with(']') {
        &trimmed[1..trimmed.len() - 1]
    } else {
        trimmed
    };

    // Split by comma and clean up
    Ok(inner
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect())
}

/// Validate a scope pattern (glob pattern for file access control)
///
/// Phase 3: Ensures the scope pattern is valid and doesn't contain path traversal.
/// Returns Ok(()) if valid, Err if invalid.
///
/// # Examples
/// - `"**"` - all files
/// - `"src/**/*.rs"` - all Rust files in src/
/// - `"docs/*.md"` - all Markdown files in docs/
/// - `"!secret/**"` - exclude secret/ (if supported by glob crate)
fn validate_scope_pattern(pattern: &str) -> ErgataiResult<()> {
    // Check for path traversal attempts
    if pattern.contains("..") {
        return Err(ErgataiError::InvalidPath(
            "Scope pattern cannot contain '..' (path traversal)".to_string(),
        ));
    }

    // Check for absolute paths
    if pattern.starts_with('/') || pattern.starts_with('\\') {
        return Err(ErgataiError::InvalidPath(
            "Scope pattern must be relative, not absolute".to_string(),
        ));
    }

    // Validate glob pattern syntax (using glob crate)
    match glob::Pattern::new(pattern) {
        Ok(_) => Ok(()),
        Err(e) => Err(ErgataiError::InvalidArgument(format!(
            "Invalid glob pattern '{}': {}",
            pattern, e
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_dag() {
        let markdown = r#"
## Task A
- **agent**: agent-a
- **task**: tasks/a.md

## Task B
- **agent**: agent-b
- **task**: tasks/b.md

## Task C
- **agent**: agent-c
- **task**: tasks/c.md
- **depends_on**: [Task A, Task B]
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        assert_eq!(graph.nodes.len(), 3);

        // IDs are auto-generated UUIDs
        for node in &graph.nodes {
            assert!(!node.id.is_empty());
            // Verify it's a valid UUID format
            assert!(Uuid::parse_str(&node.id).is_ok());
        }
    }

    #[test]
    fn test_with_parent() {
        let markdown = r#"
## Root Task
- **agent**: coordinator
- **task**: tasks/root.md

### Sub Task
- **agent**: worker
- **task**: tasks/sub.md
- **parent**: Root Task
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        assert_eq!(graph.nodes.len(), 2);

        // Sub task should depend on Root Task
        let sub = &graph.nodes[1];
        assert_eq!(sub.task, "Sub Task");

        // Find root node's UUID
        let root = &graph.nodes[0];
        assert_eq!(root.task, "Root Task");

        // Sub should depend on root's UUID
        assert_eq!(sub.depends_on.len(), 1);
        assert_eq!(sub.depends_on[0], root.id);
    }

    #[test]
    fn test_with_metadata() {
        let markdown = r#"
## Task
- **agent**: worker
- **task**: path/to/task.md
- **input**: {{user_query}}
- **custom_field**: custom_value
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        let node = &graph.nodes[0];
        assert_eq!(node.agent, "worker");
        assert_eq!(node.input, Some("{{user_query}}".to_string()));
        assert_eq!(
            node.metadata.get("task_path"),
            Some(&"path/to/task.md".to_string())
        );
        assert_eq!(
            node.metadata.get("custom_field"),
            Some(&"custom_value".to_string())
        );
    }

    #[test]
    fn test_default_agent() {
        let markdown = r#"
## Task without agent
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        let node = &graph.nodes[0];
        assert_eq!(node.agent, "agent"); // default
    }

    #[test]
    fn test_parse_array() {
        let arr = parse_array("[n1, n2, n3]").unwrap();
        assert_eq!(arr, vec!["n1", "n2", "n3"]);

        let arr = parse_array("[single]").unwrap();
        assert_eq!(arr, vec!["single"]);

        let arr = parse_array("[]").unwrap();
        assert!(arr.is_empty());
    }

    #[test]
    fn test_ready_tasks() {
        let markdown = r#"
## Task A
## Task B
## Task C
- **depends_on**: [Task A, Task B]
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        let ready = graph.ready_tasks();
        assert_eq!(ready.len(), 2); // Task A and Task B
    }

    #[test]
    fn test_scope_field() {
        let markdown = r#"
## Task A
- **agent**: agent-a
- **task**: tasks/a.md
- **scope**: src/**/*.rs

## Task B
- **agent**: agent-b
- **task**: tasks/b.md
- **scope**: **
"#;

        let graph = parse_dag_markdown(markdown).unwrap();
        assert_eq!(graph.nodes.len(), 2);

        // Task A should have scope "src/**/*.rs"
        assert_eq!(graph.nodes[0].scope, Some("src/**/*.rs".to_string()));

        // Task B should have scope "**"
        assert_eq!(graph.nodes[1].scope, Some("**".to_string()));
    }

    #[test]
    fn test_scope_validation_path_traversal() {
        let markdown = r#"
## Task A
- **agent**: agent-a
- **task**: tasks/a.md
- **scope**: ../secret/**
"#;

        let result = parse_dag_markdown(markdown);
        // Should succeed but scope should be ignored (not set)
        assert!(result.is_ok());
        let graph = result.unwrap();
        assert_eq!(graph.nodes[0].scope, None); // Invalid scope ignored
    }

    #[test]
    fn test_scope_validation_absolute_path() {
        let markdown = r#"
## Task A
- **agent**: agent-a
- **task**: tasks/a.md
- **scope**: /etc/passwd
"#;

        let result = parse_dag_markdown(markdown);
        assert!(result.is_ok());
        let graph = result.unwrap();
        assert_eq!(graph.nodes[0].scope, None); // Invalid scope ignored
    }

    #[test]
    fn test_scope_validation_invalid_glob() {
        let markdown = r#"
## Task A
- **agent**: agent-a
- **task**: tasks/a.md
- **scope**: [invalid
"#;

        let result = parse_dag_markdown(markdown);
        assert!(result.is_ok());
        let graph = result.unwrap();
        assert_eq!(graph.nodes[0].scope, None); // Invalid glob pattern ignored
    }

    #[test]
    fn test_validate_scope_pattern() {
        // Valid patterns
        assert!(validate_scope_pattern("**").is_ok());
        assert!(validate_scope_pattern("src/**/*.rs").is_ok());
        assert!(validate_scope_pattern("docs/*.md").is_ok());
        assert!(validate_scope_pattern("tests/**/unit/**").is_ok());

        // Invalid patterns
        assert!(validate_scope_pattern("../secret").is_err());
        assert!(validate_scope_pattern("/absolute/path").is_err());
        assert!(validate_scope_pattern("[invalid").is_err());
    }
}
